### ISSUE TITLE
One function: flexion.replace(tokenlist, lemma, newlemma)

### ISSUE THREAD

**Issue by ulf1** [ulf1/flexion#6]
### Todo

- [ ] Code function in Jupyter
- [ ] Add to readme
- [ ] brainstorm many unit test cases

### Datatype
```
tokenlist: [{**conllu.token, morphemes: []}, ...]
lemma: str
newlemma: {lemma: str, morphemes: []}
return modifiedstring: List[str]
```
